Repository UKRIN-MAPS/ukat, pull requests merged in 2022-01, with the labels that each got.

#176 Deleting "misc" and "preproc" folders
  .github/workflows/reference_manual.yml
  misc/README.md
  misc/renaming_repository/README.md
  misc/renaming_repository/images/1_forks.JPG
  misc/renaming_repository/images/2_forks_after_renaming_fnerys_fork.JPG
  ukat/__init__.py
  ukat/preproc/__init__.py
  ukat/preproc/dwi.py
  ukat/preproc/sitkutil.py
  ukat/preproc/tests/__init__.py
  ukat/preproc/tests/test_dwi.py
  ukat/preproc/tests/test_sitkutil.py
Labels: type:maintenance :electric_plug:

#175 TKV
  .github/workflows/python-CI.yml
  README.md
  requirements.txt
  setup.py
  tutorials/segmentation.ipynb
  ukat/__init__.py
  ukat/segmentation/__init__.py
  ukat/segmentation/tests/__init__.py
  ukat/segmentation/tests/test_whole_kidney.py
  ukat/segmentation/whole_kidney.py
Labels: type:new-feature :sparkles:

#172 B0 Map correction added for when the unwrapping isn't complete
  ukat/mapping/b0.py
  ukat/mapping/tests/test_b0.py
  ukat/utils/tools.py
Labels: type:enhancement :hammer_and_wrench:

#182 MTR bug fixes
  ukat/data/fetch.py
  ukat/data/tests/test_fetch.py
  ukat/mapping/mtr.py
Labels: type:bug :mosquito:

#181 Minor Github Actions fixes
  .github/workflows/python_CI.yml
  .github/workflows/reference_manual.yml
Labels: type:maintenance :electric_plug:

#179 MOLLI T1 Mapping
  requirements.txt
  tutorials/t1_calculation.ipynb
  ukat/data/README.md
  ukat/data/fetch.py
  ukat/data/t1/README.md
  ukat/data/tests/test_fetch.py
  ukat/mapping/t1.py
  ukat/mapping/tests/test_t1.py
Labels: type:enhancement :hammer_and_wrench:
